import numpy as np
from nistrng import *


def validate_randomness(filename):
    print(f"Loading data from {filename}...")

    # 1. Read the raw text file (which contains '1' and '0' strings)
    with open(filename, 'r') as f:
        binary_string = f.read()

    print(f"Total bits loaded: {len(binary_string)}")

    # 2. CRITICAL FIX: Convert the string into a numpy array of int8
    binary_sequence = np.array([int(bit) for bit in binary_string], dtype=np.int8)

    # 3. Check the eligibility of tests based on sequence length
    eligible_battery = check_eligibility_all_battery(binary_sequence, SP800_22R1A_BATTERY)

    print("\nStarting NIST SP 800-22 Tests. This may take several minutes...")

    # 4. Run the tests
    results = run_all_battery(binary_sequence, eligible_battery, False)

    # 5. Print the Results Table
    print("\n--- NIST SP 800-22 TEST RESULTS ---")
    print(f"{'Test Name':<35} | {'P-Value':<20} | {'Status'}")
    print("-" * 65)

    passed_tests = 0
    for result, elapsed_time in results:
        # A test passes if the p-value is >= 0.01
        status = "PASS" if result.passed else "FAIL"
        if result.passed:
            passed_tests += 1

        print(f"{result.name:<35} | {result.score:<20.6f} | {status}")

    print("-" * 65)
    print(f"Total Passed: {passed_tests} / {len(results)}")

    if passed_tests == len(results):
        print("CONCLUSION: The sequence is CRYPTOGRAPHICALLY RANDOM.")
    else:
        print("CONCLUSION: The sequence shows non-random patterns.")


if __name__ == "__main__":
    # Ensure this matches the file generated by your Qiskit script
    validate_randomness("quantum_random_data.txt")